### ISSUE TITLE
Feature Suggest: AI command action that opens in scratchpad

### ISSUE THREAD

**Issue by dantosXD** [nbonamy/witsy#14]
I'd like a "Send to Scratchpad" as an action option in the AI Command menu. This would let me start a draft with an AI command and then refine it in the scratchpad.

![image](https://github.com/user-attachments/assets/a93c026d-f3fc-4807-a8a0-94a6ef739df5)

**Comment by nbonamy** [comment]
I am thinking of redesigning AI commands output because I feel that the action is more contextual (what you are doing) vs the command itself. So thinking having a result window similar to Prompt Anywhere the actions will be showed at the bottom:
- copy
- replace
- insert below
- send to chat
- send to scratchpad

**Comment by dantosXD** [comment]
Cool, I will keep using this really amazing software and wait for the updates. Thank you for all you do.

**Comment by nbonamy** [comment]
This is how it looks as of now. Thoughts?

https://github.com/user-attachments/assets/a1f6a2cb-3b7a-4c3c-bba6-93d5d5150c31

**Comment by nbonamy** [comment]
Released in 1.24.0. Will close in a few days if no feedback

**Comment by dantosXD** [comment]
It is even better than I was envisioning! TY for this great product.
